sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tBAFBtsfWqhP2wvM4cX
      access-key-secret: 5xMrplChFdaAzi1iEfapezzkRWmP8j
      bucket-name: web-tlias-harper
  redis:
    host: localhost
    auth: 123456
    port: 6379
    database: 0
